subjekte = [
    "Paul als kleines Kind",
    "Mika, der Clown,",
    "Die allseits bekannte Ameise Jon",
    "Die Oma Hildegart",
    "Mika, der schlaue Hase,",
    "Lucy, der stärkste Wikinger im ganzen Dorf,",
    "Hanno, der Hund",
    "Elis",
    "Hanno, der Bürohase",
    "Ben, der auf dem Bobbicar immer umkippt,",
    "Deine Mutter",
    "Dein Fater" "Jon der Bauleiterbaum",
    "Tim, der traurige Toaster,",
    "Mülli, der kleine Mülleimer,",
    "Bob Banane",
    "Paul, der heimliche Comiczeichner,",
    "Mika, der selbsternannte Superheld,",
    "Jon, der Ameisenflüsterer mit einem Plan,",
    "Oma Hildegart, die Undercover-Rockstar-Oma,",
    "Hanno, der Hund, der glaubt, er sei eine Katze,",
    "Elis, die Erfinderin mit zu vielen Ideen,",
    "Ben, der Bobbicar-Stuntma,",
    "Lucy, die Wikinger-Chefin mit einem Teddy als Berater,",
    "Peter, der Pauker,",
    "Popstar Kevin",
    "Der einjährige Bob",
    "Der EINE und EINZIGE Jon",
    "Bobby, das Bobbycar – wer hätte es gedacht –,",
]

prädikate_und_objekte = [
    "baut ein Legohaus",
    "läuft auf den Händen",
    "spielt am Laptop",
    "tattowiert sich",
    "isst Süßigkeiten",
    "demonstriert",
    "fährt Traktor",
    "krabbelt auf eine Ameise",
    "Malt einen Kühlschrank",
    "Isst sein Bobbycar zum Frühstück",
    "baut eine verrückte Maschine aus alten Socken",
    "versucht, die Schwerkraft mit Löffeln zu besiegen",
    "malt ein Meisterwerk mit Ketchup und Senf",
    "startet einen Blog über das Leben als Gartenstatue",
    "organisiert eine Geheimagenten-Mission im Vorgarten",
    "erfindet eine neue Sportart mit Gummibändern und Marshmallows",
    "führt Regie bei einem Film, in dem nur Haustiere mitspielen",
]

adverbialbestimmungen = [
    "unter dem schönsten Baum des Landes",
    "in China, direkt neben einem umfallenden Reissack,",
    "auf den rosa-weißen Wolken",
    "im weißen Wunderwald",
    "unter den Rädern eines purpurtoten Bobbycars und voller böser Schmerzen",
    "im geheimen Labor unter dem Bett",
    "auf dem Dachboden, umgeben von mysteriösen alten Kisten",
    "in der Schulkantine, als alle anderen essen",
    "im Garten, getarnt als unscheinbare Pflanze",
    "im Wohnzimmer, umgeben von ahnungslosen Erwachsenen",
]

adverbien = [
    "lächelnd und doch angespannt",
    "und immer selbstbewusst und lustig",
    "voller rosa-roter Zuckerwate",
    "mit einer Spur von Genie und Wahnsinn",
    "als ob morgen die Welt untergeht",
    "mit der Eleganz eines Elefanten auf Rollschuhen",
    "als ob es das Normalste der Welt wäre",
    "wie ein Weltmeister",
    "mit einem geheimnisvollen Lächeln im Gesicht",
    "wie ein Meisterdetektiv auf einer heißen Spur",
    "als wäre jeden Tag ein großes Abenteuer",
    "mit einer Prise Verrücktheit und einem Hauch von Magie",
    "als ob er/sie gerade einen genialen Einfall hätte",
]

twists = [
    "und das trotz der kleinen Hände",
    "aber das ging auch schon mal schneller",
    "mit ein bisschen Glück und viel Geschick",
    "und du wurdest nicht um Erlaubnis gebeten",
    "aber das wollte eigentlich niemand wissen",
    "weil die Mama die beste auf der ganzen weiten Welt ist",
    "und mein Papa hat eine Pistole",
    "und das ganze Haus wackelt",
    "aber vergisst dabei die Zeit",
    "und stellt fest, dass das Leben kein Videospiel ist",
    "und wird dabei zum unerwarteten Helden der Nachbarschaft",
    "aber am Ende geht alles schief, wie immer",
    "und alle waren total überrascht",
    "aber niemand konnte aufhören zu lachen",
    "und plötzlich wurde alles viel spannender",
    "und dann kam ein Ufo vorbei",
    "aber es bleibt alles so wie immer",
    "und fällt aus allen Wolken",
    "aber die Welt dreht sich immernoch",
    "doch der eifelturm steht immernoch",
]
